"""
src/report_generator.py — Human-readable report generation.

Takes the verdict, reasoning, feature values, and optionally annotated images
to produce:
  1. A plain-text console report
  2. An annotated summary image (leaf with vein overlay + text panel)
  3. Optionally, an HTML report for richer formatting

The report is designed for non-expert users: plain language, clear layout,
with the technical feature values available for reference.
"""

import cv2
import numpy as np
import os
import sys
from datetime import datetime

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
from config.thresholds import (
    YELLOW_RATIO_DEFICIENT,
    EXG_HEALTHY_LOW,
    DGCI_HEALTHY_LOW,
    INTERVEINAL_CONTRAST_THRESHOLD,
    COLOR_SPATIAL_VARIANCE_MAX,
    VEIN_DENSITY_DEFICIENT,
    VEIN_THICKNESS_DEFICIENT_HIGH,
    UNHEALTHY_REGION_MIN_AREA,
)


def generate_text_report(image_id: str,
                          verdict_result: dict,
                          features: dict,
                          validation: dict = None) -> str:
    """
    Generate a plain-text report summarizing the health assessment.

    Args:
        image_id: Identifier for the leaf image pair.
        verdict_result: Output dict from decision_engine.evaluate().
        features: Feature dict from feature_extraction.extract_all_features().
        validation: Segmentation validation dict (optional).

    Returns:
        Multi-line formatted text report string.
    """
    lines = []

    # Header
    lines.append("=" * 70)
    lines.append("  ROSA-SINENSIS LEAF HEALTH ASSESSMENT REPORT")
    lines.append("=" * 70)
    lines.append("")
    lines.append(f"  Image ID:      {image_id}")
    lines.append(f"  Date:          {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append(f"  Verdict:       {verdict_result['verdict']}")
    lines.append(f"  Signals:       {verdict_result['confidence_signals']} feature(s) flagged")
    lines.append("")

    # Segmentation quality
    if validation:
        lines.append("-" * 70)
        lines.append("  SEGMENTATION QUALITY")
        lines.append("-" * 70)
        status = "PASS" if validation['valid'] else "WARNING"
        lines.append(f"  Status:        {status}")
        lines.append(f"  Leaf area:     {validation['leaf_area_pixels']:,} pixels "
                      f"({validation['leaf_area_fraction']:.1%} of frame)")
        if validation['issues']:
            for issue in validation['issues']:
                lines.append(f"  ! {issue}")
        lines.append("")

    # Feature values
    lines.append("-" * 70)
    lines.append("  MEASURED FEATURES")
    lines.append("-" * 70)
    lines.append("")
    lines.append("  Vein Architecture (Secondary Factors):")
    lines.append(f"    * Vein density:          {features.get('vein_density', 0):.6f}  (Fail if < {VEIN_DENSITY_DEFICIENT:.6f})")
    lines.append(f"    * Vein thickness (avg):  {features.get('vein_thickness_avg', 0):.2f} px (Fail if > {VEIN_THICKNESS_DEFICIENT_HIGH:.2f})")
    lines.append(f"    * Branch points:         {features.get('branch_point_count', 0)}")
    lines.append(f"    * Vein pixels:           {features.get('vein_pixel_count', 0):,}")
    lines.append(f"    * Leaf area:             {features.get('leaf_area_pixels', 0):,} px")
    lines.append("")
    lines.append("  Color / Chlorosis (Primary Factors):")
    lines.append(f"    * Mean hue:              {features.get('mean_hue', 0):.1f}")
    lines.append(f"    * Mean saturation:       {features.get('mean_saturation', 0):.1f}")
    lines.append(f"    * Yellow pixel ratio:    {features.get('yellow_pixel_ratio', 0):.2%}  (Fail if > {YELLOW_RATIO_DEFICIENT:.2%})")
    lines.append(f"    * Excess Green Index:    {features.get('excess_green_index', 0):.6f}  (Fail if < {EXG_HEALTHY_LOW:.6f})")
    lines.append(f"    * DGCI:                  {features.get('dgci', 0):.6f}  (Fail if < {DGCI_HEALTHY_LOW:.6f})")
    lines.append(f"    * Interveinal contrast:  {features.get('interveinal_contrast', 0):.1f}  (Fail if > {INTERVEINAL_CONTRAST_THRESHOLD:.1f})")
    lines.append(f"    * Color spatial var:     {features.get('color_spatial_variance', 0):.1f}  (Fail if > {COLOR_SPATIAL_VARIANCE_MAX:.1f})")
    lines.append("")

    # Reasoning
    lines.append("-" * 70)
    lines.append("  ANALYSIS REASONING")
    lines.append("-" * 70)
    lines.append("")
    # Indent each line of the reasoning
    for line in verdict_result['reasoning'].split('\n'):
        lines.append(f"  {line}")
    lines.append("")

    if verdict_result['verdict'] != "Leaf Health Status: HEALTHY":
        lines.append(f"  Flagged regions visualized in {image_id}_unhealthy_regions.jpg")
        lines.append("")

    # Footer
    lines.append("=" * 70)
    lines.append("  This report was generated by a rule-based image analysis system.")
    lines.append("  It is NOT a diagnostic tool. For definitive assessment, consult")
    lines.append("  a plant specialist or conduct laboratory soil/tissue testing.")
    lines.append("=" * 70)

    return "\n".join(lines)


def generate_annotated_image(original_image: np.ndarray,
                              debug_overlay: np.ndarray,
                              verdict_result: dict,
                              features: dict,
                              image_id: str = "") -> np.ndarray:
    """
    Create a side-by-side annotated image: original leaf + vein overlay + text panel.

    Args:
        original_image: Preprocessed BGR leaf image.
        debug_overlay: BGR image with vein skeleton overlay.
        verdict_result: Output dict from decision_engine.evaluate().
        features: Feature dict from feature_extraction.extract_all_features().
        image_id: Identifier string for the leaf.

    Returns:
        Combined BGR image suitable for saving.
    """
    h, w = original_image.shape[:2]

    # Create text panel (same height as images, fixed width)
    panel_width = 400
    panel = np.zeros((h, panel_width, 3), dtype=np.uint8)
    panel[:] = (30, 30, 30)  # dark gray background

    # Write text on panel
    font = cv2.FONT_HERSHEY_SIMPLEX
    font_scale = 0.45
    color_white = (255, 255, 255)
    color_green = (100, 255, 100)
    color_yellow = (100, 255, 255)
    color_red = (100, 100, 255)

    # Verdict color
    verdict = verdict_result['verdict']
    if verdict == "Healthy":
        verdict_color = color_green
    elif verdict == "Possibly Deficient":
        verdict_color = color_yellow
    else:
        verdict_color = color_red

    y = 30
    line_height = 22

    cv2.putText(panel, "LEAF HEALTH REPORT", (10, y), font, 0.6, color_white, 1)
    y += line_height + 5

    if image_id:
        cv2.putText(panel, f"ID: {image_id}", (10, y), font, font_scale, color_white, 1)
        y += line_height

    cv2.putText(panel, f"Verdict: {verdict}", (10, y), font, 0.55, verdict_color, 1)
    y += line_height + 10

    # Feature values
    cv2.putText(panel, "-- Vein Features --", (10, y), font, font_scale, color_white, 1)
    y += line_height
    cv2.putText(panel, f"Density: {features.get('vein_density', 0):.5f}", (10, y),
                font, font_scale, color_white, 1)
    y += line_height
    cv2.putText(panel, f"Thickness: {features.get('vein_thickness_avg', 0):.2f}px", (10, y),
                font, font_scale, color_white, 1)
    y += line_height
    cv2.putText(panel, f"Branches: {features.get('branch_point_count', 0)}", (10, y),
                font, font_scale, color_white, 1)
    y += line_height + 10

    cv2.putText(panel, "-- Color Features --", (10, y), font, font_scale, color_white, 1)
    y += line_height
    cv2.putText(panel, f"Yellow ratio: {features.get('yellow_pixel_ratio', 0):.1%}", (10, y),
                font, font_scale, color_white, 1)
    y += line_height
    cv2.putText(panel, f"ExG: {features.get('excess_green_index', 0):.4f}", (10, y),
                font, font_scale, color_white, 1)
    y += line_height
    cv2.putText(panel, f"DGCI: {features.get('dgci', 0):.4f}", (10, y),
                font, font_scale, color_white, 1)
    y += line_height
    cv2.putText(panel, f"Saturation: {features.get('mean_saturation', 0):.1f}", (10, y),
                font, font_scale, color_white, 1)
    y += line_height
    cv2.putText(panel, f"Interveinal: {features.get('interveinal_contrast', 0):.1f}", (10, y),
                font, font_scale, color_white, 1)
    y += line_height + 10

    # Flagged features
    flags = verdict_result.get('flags', [])
    if flags:
        cv2.putText(panel, f"-- Flags ({len(flags)}) --", (10, y),
                     font, font_scale, color_yellow, 1)
        y += line_height
        for flag in flags[:5]:  # Show up to 5 flags
            text = f"! {flag['feature']} ({flag['type']})"
            cv2.putText(panel, text, (10, y), font, font_scale - 0.05, color_yellow, 1)
            y += line_height

    # Resize images to match panel height if needed
    orig_resized = cv2.resize(original_image, (w, h))
    overlay_resized = cv2.resize(debug_overlay, (w, h))

    # Concatenate: original | overlay | text panel
    combined = np.hstack([orig_resized, overlay_resized, panel])

    return combined


def save_report(report_text: str, output_path: str) -> str:
    """
    Save a text report to a file.

    Args:
        report_text: The formatted report string.
        output_path: Path to save the report file.

    Returns:
        The output path.
    """
    os.makedirs(os.path.dirname(output_path) or '.', exist_ok=True)
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(report_text)
    return output_path


def save_annotated_image(image: np.ndarray, output_path: str) -> str:
    """
    Save an annotated image to disk.

    Args:
        image: BGR image to save.
        output_path: Output file path.

    Returns:
        The output path.
    """
    os.makedirs(os.path.dirname(output_path) or '.', exist_ok=True)
    cv2.imwrite(output_path, image)
    return output_path


def generate_unhealthy_regions_image(overlay_image: np.ndarray,
                                     features: dict,
                                     verdict_result: dict) -> np.ndarray:
    """
    Circle flagged regions for failed primary factors.

    Args:
        overlay_image: The BGR image with the red vein overlay.
        features: Feature dict from feature_extraction (containing 'masks').
        verdict_result: Output dict from decision_engine.evaluate().

    Returns:
        BGR image with magenta/orange circles around flagged regions, or None if HEALTHY.
    """
    if verdict_result['verdict'] == "Leaf Health Status: HEALTHY":
        return None

    flagged_masks = []
    failed_factors = []
    
    # Identify which primary factors failed
    for flag in verdict_result.get('flags', []):
        if flag['type'] == 'primary':
            factor = flag['feature']
            if 'masks' in features and factor in features['masks']:
                flagged_masks.append(features['masks'][factor])
                failed_factors.append(factor)

    if not flagged_masks:
        return overlay_image.copy()

    # Union all failed primary masks
    union_mask = np.zeros_like(flagged_masks[0])
    for m in flagged_masks:
        union_mask = cv2.bitwise_or(union_mask, m)

    # Morphological cleanup
    kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (5, 5))
    cleaned_mask = cv2.morphologyEx(union_mask, cv2.MORPH_OPEN, kernel)
    cleaned_mask = cv2.morphologyEx(cleaned_mask, cv2.MORPH_CLOSE, kernel)

    # Find contours
    contours, _ = cv2.findContours(cleaned_mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

    result_image = overlay_image.copy()
    circle_color = (255, 0, 255)  # Magenta

    for cnt in contours:
        area = cv2.contourArea(cnt)
        if area >= UNHEALTHY_REGION_MIN_AREA:
            # Fit minimum enclosing circle
            (x, y), radius = cv2.minEnclosingCircle(cnt)
            center = (int(x), int(y))
            # Draw circle with 5px padding
            cv2.circle(result_image, center, int(radius) + 5, circle_color, 2)

    # Add legend at the top
    font = cv2.FONT_HERSHEY_SIMPLEX
    legend_text = f"Flagged by: {', '.join(failed_factors)}"
    cv2.putText(result_image, legend_text, (20, 30), font, 0.7, circle_color, 2)

    return result_image
